- name: install epel
  yum:
    name: epel-release
    state: present

- name: install remi
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: install httpd and php7
  yum:
    enablerepo: remi-php74
    name:
      - httpd
      - php
      - php-cli
      - php-common
      - php-devel
      - php-fpm
      - php-mbstring
      - php-mysqlnd
      - php-pdo
      - php-gd
      - php-xml
      - php-zip
  notify:
    - restart httpd

- name: create the configuration file
  template: src=role-web/templates/main.conf.j2 dest=/etc/httpd/conf.d/main.conf owner=root group=root mode=0644
  notify:
    - restart httpd

- name: create the php configuration file
  template: src=role-web/templates/main.ini.j2 dest=/etc/php.d/main.ini owner=root group=root mode=0644
  notify:
    - restart httpd

- name: check directory for main
  stat: path=/var/www/main
  register: directory_main
  tags: main

- block:
  - name: create directory for main
    file:
      dest: /var/www/main
      owner: "{{ web.username }}"
      group: "{{ web.username }}"
      mode: 0755
      state: directory

  - name: create directory for html
    file:
      dest: /var/www/main/html
      owner: "{{ web.username }}"
      group: "{{ web.username }}"
      mode: 0755
      state: directory

  - name: create the index file
    template: src=role-web/templates/index.php.j2 dest=/var/www/main/html/index.php owner="{{ web.username }}" group="{{ web.username }}" mode=0644

  when: not directory_main.stat.exists
  tags: main

- name: enable autostart for httpd
  service: name=httpd enabled=yes
